project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - .nojekyll
    - CNAME

website:
  title: ""
  search: false
  navbar:
    search: false
    title: "Claude for Teaching & Research"
    left:
      - href: index.qmd
        text: Home
      - href: "https://jgsb.zoom.us/j/95657980099?pwd=Ve5TMEaaBRQnhWnhnpaJFDHevFIbRU.1"
        text: Zoom

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
