project:
  output-dir: ../slides-html
  render:
    - "*.qmd"

format:
  revealjs:
    theme: [default, revealjs-style.scss]
    highlight-style: monokai
    slide-number: 'c/t'
    transition: fade
    navigation-mode: linear
    width: 1920
    height: 1080
    margin: 0.05
    center: true
    auto-stretch: false
